# Generated by Django 3.2.7 on 2021-09-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned.'),), 'verbose_name': 'BookInstance', 'verbose_name_plural': 'BookInstances'},
        ),
    ]
